"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from django_filters.conf import settings
from dotenv import load_dotenv
from datetime import timedelta
from storages.backends.s3 import S3Storage
from storages.backends.s3boto3 import S3Boto3Storage

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') in ['True', 'true', '1']

LOGGING = {
    'version': 1,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
}

FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')

CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if origin.strip()]

ORIGIN_HTTPS_ON = os.getenv('ORIGIN_HTTPS_ON', 'False') in ['True', 'true', '1']
ORIGIN_CROSS_DOMAIN = os.getenv('ORIGIN_CROSS_DOMAIN', 'False') in ['True', 'true', '1']
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', '').split(',')  
CORS_ALLOW_CREDENTIALS = True
  

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',

    # Local apps
    'apps.users.apps.UsersConfig',
    'apps.products.apps.ProductsConfig',
    'apps.orders.apps.OrdersConfig',
    'apps.carts.apps.CartsConfig',
    # 'apps.payments.apps.PaymentsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'NAME': os.getenv('DB_NAME'),
    }
}

# Custom user model
AUTH_USER_MODEL = 'users.UserAuth'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'vi'
TIME_ZONE = 'Asia/Ho_Chi_Minh'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

class StaticStorage(S3Boto3Storage):
    location = 'static'
    default_acl = 'public-read'

    def url(self, name, headers=None, expire=None, http_method=None):
        # Dùng globals().get() để đọc an toàn các biến đã khai báo ở phía trên file settings.py
        protocol = globals().get('AWS_S3_URL_PROTOCOL', 'http')
        domain = globals().get('AWS_S3_CUSTOM_DOMAIN', '')

        if domain:
            return f"{protocol}://{domain}/static/{name}"
        return super().url(name, headers, expire, http_method)


class MediaStorage(S3Boto3Storage):
    location = 'media'
    default_acl = 'public-read'

    def url(self, name, headers=None, expire=None, http_method=None):
        protocol = globals().get('AWS_S3_URL_PROTOCOL', 'http')
        domain = globals().get('AWS_S3_CUSTOM_DOMAIN', '')

        if domain:
            return f"{protocol}://{domain}/media/{name}"
        return super().url(name, headers, expire, http_method)
    

AWS_ACCESS_KEY_ID       = os.getenv('AWS_ACCESS_KEY_ID') or None
AWS_SECRET_ACCESS_KEY   = os.getenv('AWS_SECRET_ACCESS_KEY') or None
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME') or None
AWS_S3_REGION_NAME      = os.getenv('AWS_S3_REGION_NAME', 'us-east-1')
AWS_S3_ENDPOINT_URL     = os.getenv('AWS_S3_ENDPOINT_URL') or None
AWS_S3_CUSTOM_DOMAIN    = os.getenv('AWS_S3_CUSTOM_DOMAIN') or None
AWS_S3_URL_PROTOCOL     = os.getenv('AWS_S3_URL_PROTOCOL', 'http')

if AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and AWS_STORAGE_BUCKET_NAME:
    STORAGES = { # Cấu hình file được Backend gửi lên lưu vào folder nào trên S3 Bucket
        "default": {
            "BACKEND": "config.settings.MediaStorage",
        },
        "staticfiles": {
            "BACKEND": "config.settings.StaticStorage",
        },
    }

    if DEBUG: # Cấu hình dành riêng cho LocalStack
        AWS_S3_USE_SSL = False
        AWS_S3_VERIFY = False
        AWS_S3_ADDRESSING_STYLE = "path"    # Ép dùng path-style: http://localhost:4566/bucket/file
        
        # Link render cho Browser/Client (Dùng trực tiếp Endpoint của LocalStack)
        STATIC_URL = f"{AWS_S3_URL_PROTOCOL}://{AWS_S3_CUSTOM_DOMAIN}/static/"
        MEDIA_URL = f"{AWS_S3_URL_PROTOCOL}://{AWS_S3_CUSTOM_DOMAIN}/media/"
    else: # Cấu hình dành cho Production (AWS thật)
        AWS_S3_USE_SSL = True
        AWS_S3_VERIFY = True
        AWS_S3_ADDRESSING_STYLE = "virtual" # Mặc định AWS dùng Virtual-style
        
        if AWS_S3_CUSTOM_DOMAIN: # Nếu dùng CloudFront hoặc Domain riêng
            STATIC_URL = f"{AWS_S3_URL_PROTOCOL}://{AWS_S3_CUSTOM_DOMAIN}/static/"
            MEDIA_URL = f"{AWS_S3_URL_PROTOCOL}://{AWS_S3_CUSTOM_DOMAIN}/media/"
        else: # Nếu dùng link mặc định của S3
            STATIC_URL = f"{AWS_S3_URL_PROTOCOL}://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/static/"
            MEDIA_URL = f"{AWS_S3_URL_PROTOCOL}://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/media/"
else: # --- Fallback về Local Storage nếu thiếu config S3 ---
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    
    STATIC_URL = '/static/'
    MEDIA_URL = '/media/'

    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
    # STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static_fe'), os.path.join(BASE_DIR, 'static_admin')]
    STATIC_ROOT = os.path.join(BASE_DIR, 'static_root')



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Third-party app settings



REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'utils.custom_exception_handler.custom_exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': (
            'apps.authentication.authenticate.CustomJWTAuthentication',
        ),
    'DEFAULT_PERMISSION_CLASSES': (
            'rest_framework.permissions.IsAuthenticated',
        ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}



SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True, # Bonus: Cập nhật thời gian login cuối của user

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY, # Dùng secret key của project để ký token

    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'TOKEN_OBTAIN_PAIR_SERIALIZER': 'apps.users.authenticate.CustomTokenObtainPairSerializer',   # Trỏ đến class custom serializer 
}

PAYOS_CLIENT_ID     = os.getenv('PAYOS_CLIENT_ID')
PAYOS_API_KEY       = os.getenv('PAYOS_API_KEY')
PAYOS_CHECKSUM_KEY  = os.getenv('PAYOS_CHECKSUM_KEY')