# Generated by Django 5.2.13 on 2026-05-15 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_order_order_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_link',
        ),
    ]
