# Generated by Django 5.2.13 on 2026-05-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_color_orderitem_product_main_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link thanh toán'),
        ),
    ]
