# Generated by Django 5.2.13 on 2026-05-12 06:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('specs', models.JSONField(blank=True, null=True, verbose_name='Thông số kỹ thuật')),
                ('base_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(1000)], verbose_name='Giá cơ bản (Giá thấp nhất)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Danh sách sản phẩm',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Hình ảnh')),
                ('is_main', models.BooleanField(default=False, verbose_name='Hình ảnh chính')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Hình ảnh sản phẩm',
                'verbose_name_plural': 'Thư viện ảnh sản phẩm',
                'db_table': 'product_images',
                'ordering': ['-is_main', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Mã phiên bản (SKU)')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(1000)], verbose_name='Giá')),
                ('version', models.CharField(max_length=255, verbose_name='Phiên bản khác nhau của sản phẩm')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Màu sắc')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='Sản phẩm')),
                ('variant_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_images', to='products.productimage', verbose_name='Ảnh phiên bản')),
            ],
            options={
                'verbose_name': 'Phiên bản sản phẩm',
                'verbose_name_plural': 'Các phiên bản sản phẩm',
                'db_table': 'product_variants',
            },
        ),
    ]
