# Generated by Django 5.2.13 on 2026-05-12 12:34

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=apps.products.models.rename_image, verbose_name='Hình ảnh'),
        ),
    ]
