# Generated by Django 5.2.13 on 2026-05-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productvariant_unique_variant_per_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=200, verbose_name='Số lượng tồn kho'),
        ),
    ]
